#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  8 16:12:40 2019

@author: zhangguangwei
"""

import cv2
import numpy as np
#import matplotlib.pyplot as plt
import os
from math import hypot
from tkinter import Tk
import csv
from tkinter.filedialog import askopenfilenames

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
root1 = Tk()
filez = askopenfilenames(parent = root1, title = 'Choose file')

#print(root1.tk.splitlist(filez))

for fullFileName in root1.tk.splitlist(filez):
    filename = fullFileName
    (root, ext) =os.path.splitext(filename) 
    
    
    
    



lick = []

with open(root+ext,'r+') as f1:
    plots = csv.reader(f1,delimiter=',')
    for row in plots:
        lick.append((float(row[1])))


lick_array = np.array(lick)

a = np.append(lick_array,[[0],[0]])

b= np.reshape(a,(250,50))
c= np.transpose(b)        

sns.heatmap(c, cmap="YlGnBu")
        
        
ax2 = plt.subplot(312)
ax2.plot(lick[1:len(lick)],label ='Speed mm/frame')
ax2.set_ylabel("speed mm/frame")
ax2.set_xlabel("time (frame) 30fps")
ax2.set_ylim([0,1000])